# Generated by Django 2.2.6 on 2019-10-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterBase',
            fields=[
                ('Encounter_ID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Clinic_ID', models.CharField(max_length=100)),
                ('Encounter_DateTime', models.DateTimeField()),
                ('Encounter_Description', models.TextField()),
                ('Provider_ID_x', models.BigIntegerField()),
                ('Provider_NPI', models.BigIntegerField()),
                ('Provider_Name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Patient_DOB', models.DateField()),
                ('Patient_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('Episode_ID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Active', models.BooleanField(default=True)),
                ('Disposition', models.CharField(choices=[('ReleasedWithoutLimitations', 'Released without limitations'), ('ReleasedWithLimitations', 'Released with limitations'), ('SickAtHome', 'Sick at Home'), ('Admitted', 'Admitted')], default='SickAtHome', max_length=100)),
                ('SOAP_Note', models.TextField()),
                ('CC', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='member_data.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('encounterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_data.EncounterBase')),
                ('Pharmacy_Name', models.CharField(max_length=100)),
                ('Prescription', models.CharField(max_length=100)),
                ('Drug_Name', models.CharField(max_length=100)),
                ('Units_y', models.CharField(max_length=100)),
                ('Days_Of_Supply', models.BigIntegerField()),
                ('Dispense_Date', models.DateTimeField()),
                ('Dispense_Qty', models.BigIntegerField()),
                ('Dose', models.BigIntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_encounters', to='member_data.Episode')),
            ],
            bases=('member_data.encounterbase',),
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('encounterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_data.EncounterBase')),
                ('Specialty_x', models.CharField(max_length=100)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_encounters', to='member_data.Episode')),
            ],
            bases=('member_data.encounterbase',),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('encounterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_data.EncounterBase')),
                ('Test_ID', models.CharField(max_length=100)),
                ('Order_ID_x', models.CharField(max_length=100)),
                ('Test_Name', models.CharField(max_length=100)),
                ('Units_x', models.CharField(max_length=100)),
                ('Result_Name', models.CharField(max_length=100)),
                ('Result_Status', models.CharField(max_length=100)),
                ('Date_Collected', models.DateTimeField()),
                ('Date_Resulted', models.DateTimeField()),
                ('Numeric_Result', models.BigIntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_encounters', to='member_data.Episode')),
            ],
            bases=('member_data.encounterbase',),
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('encounterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_data.EncounterBase')),
                ('Specialty_x', models.CharField(max_length=100)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_encounters', to='member_data.Episode')),
            ],
            bases=('member_data.encounterbase',),
        ),
    ]
