# Generated by Django 2.2.6 on 2019-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='DataHash',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='Active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
