# Generated by Django 2.2.6 on 2019-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='CC',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='CC',
        ),
        migrations.AddField(
            model_name='episode',
            name='CC',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
