# Generated by Django 2.2.6 on 2019-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_data', '0002_auto_20191026_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='DataHash',
        ),
        migrations.AddField(
            model_name='member',
            name='HistoryHash',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
