# Generated by Django 2.2.6 on 2019-10-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_data', '0003_auto_20191026_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='HistoryHash',
            new_name='LastHash',
        ),
        migrations.AddField(
            model_name='episode',
            name='HistoryHash',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
